# Setup
title:               Luffy's Blog
tagline:             ''
description:         'Hello World'
url:                 https://rukalchau.github.io
baseurl:             '/Luffy'
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Luffy
  url:               
  email:             rukalchau@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
